version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ./dags:/opt/airflow/dags
    - ./spark_scripts:/opt/spark_scripts
    - ./datalake:/opt/datalake
  depends_on:
    postgres:
      condition: service_healthy

services:
  # 1. DATABASE CHO AIRFLOW
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  # 2. KHỞI TẠO AIRFLOW (Tạo tài khoản admin/admin)
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_ROLE=Admin

  # 3. AIRFLOW WEBSERVER (Giao diện Port 8080)
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # 4. AIRFLOW SCHEDULER
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  # 5. SPARK MASTER (Giao diện Port 8081)
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark_scripts:/opt/spark_scripts
      - ./datalake:/opt/datalake

  # 6. SPARK WORKER (Máy cày xử lý data)
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark_scripts:/opt/spark_scripts
      - ./datalake:/opt/datalake
    depends_on:
      - spark-master

  # 7. ELASTICSEARCH (Tầng Serving Layer cho Dashboard)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Ép RAM xuống 512MB để không sập máy ảo
    ports:
      - "9200:9200"