FROM apache/airflow:2.9.1-python3.10

# Cài đặt Java (Bắt buộc để Airflow chạy được lệnh spark-submit)
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-11-jre-headless \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

USER airflow
# Copy và cài đặt thư viện Python
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt